services:
  - type: web
    name: inventario-laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - app/
        - bootstrap/
        - config/
        - database/
        - public/
        - resources/
        - routes/
        - composer.json
        - Dockerfile
        - render.yaml
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://inventario-laravel-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <tu_host_mysql>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <tu_base_de_datos>
      - key: DB_USERNAME
        value: <tu_usuario_bd>
      - key: DB_PASSWORD
        value: <tu_password_bd>
